"""Cryptographic utilities for AuthTest."""

from authtest.core.crypto.certs import (
    DEFAULT_CERT_DIR,
    DEFAULT_CERT_PATH,
    DEFAULT_KEY_PATH,
    ENV_TLS_CERT,
    ENV_TLS_CERT_DIR,
    ENV_TLS_KEY,
    CertificateError,
    CertificateInfo,
    CertificateLoadError,
    CertificateNotFoundError,
    KeyLoadError,
    TLSConfig,
    compute_certificate_fingerprint,
    ensure_tls_certificate,
    generate_private_key,
    generate_self_signed_certificate,
    get_cert_dir,
    get_cert_path,
    get_certificate_info,
    get_certificate_pem,
    get_key_path,
    get_private_key_pem,
    is_certificate_valid,
    load_certificate,
    load_pkcs12,
    load_private_key,
    save_certificate,
    save_private_key,
)
from authtest.core.crypto.tokens import (
    JWTManipulator,
    ManipulatedToken,
    ManipulationType,
    TokenManipulation,
    create_jwt_from_scratch,
    decode_jwt_parts,
    generate_signing_key_pair,
    get_private_key_pem as get_signing_key_pem,
    get_public_key_jwk,
    get_public_key_pem,
)

__all__ = [
    # Constants
    "DEFAULT_CERT_DIR",
    "DEFAULT_CERT_PATH",
    "DEFAULT_KEY_PATH",
    "ENV_TLS_CERT",
    "ENV_TLS_CERT_DIR",
    "ENV_TLS_KEY",
    # Exceptions
    "CertificateError",
    "CertificateLoadError",
    "CertificateNotFoundError",
    "KeyLoadError",
    # Data classes
    "CertificateInfo",
    "TLSConfig",
    # Certificate functions
    "compute_certificate_fingerprint",
    "ensure_tls_certificate",
    "generate_private_key",
    "generate_self_signed_certificate",
    "get_cert_dir",
    "get_cert_path",
    "get_certificate_info",
    "get_certificate_pem",
    "get_key_path",
    "get_private_key_pem",
    "is_certificate_valid",
    "load_certificate",
    "load_pkcs12",
    "load_private_key",
    "save_certificate",
    "save_private_key",
    # Token manipulation classes
    "JWTManipulator",
    "ManipulatedToken",
    "ManipulationType",
    "TokenManipulation",
    # Token manipulation functions
    "create_jwt_from_scratch",
    "decode_jwt_parts",
    "generate_signing_key_pair",
    "get_signing_key_pem",
    "get_public_key_jwk",
    "get_public_key_pem",
]
