"""Cryptographic utilities for AuthTest."""

from authtest.core.crypto.certs import (
    DEFAULT_CERT_DIR,
    DEFAULT_CERT_PATH,
    DEFAULT_KEY_PATH,
    ENV_TLS_CERT,
    ENV_TLS_CERT_DIR,
    ENV_TLS_KEY,
    CertificateError,
    CertificateInfo,
    CertificateLoadError,
    CertificateNotFoundError,
    KeyLoadError,
    TLSConfig,
    compute_certificate_fingerprint,
    ensure_tls_certificate,
    generate_private_key,
    generate_self_signed_certificate,
    get_cert_dir,
    get_cert_path,
    get_certificate_info,
    get_certificate_pem,
    get_key_path,
    get_private_key_pem,
    is_certificate_valid,
    load_certificate,
    load_pkcs12,
    load_private_key,
    save_certificate,
    save_private_key,
)

__all__ = [
    # Constants
    "DEFAULT_CERT_DIR",
    "DEFAULT_CERT_PATH",
    "DEFAULT_KEY_PATH",
    "ENV_TLS_CERT",
    "ENV_TLS_CERT_DIR",
    "ENV_TLS_KEY",
    # Exceptions
    "CertificateError",
    "CertificateLoadError",
    "CertificateNotFoundError",
    "KeyLoadError",
    # Data classes
    "CertificateInfo",
    "TLSConfig",
    # Functions
    "compute_certificate_fingerprint",
    "ensure_tls_certificate",
    "generate_private_key",
    "generate_self_signed_certificate",
    "get_cert_dir",
    "get_cert_path",
    "get_certificate_info",
    "get_certificate_pem",
    "get_key_path",
    "get_private_key_pem",
    "is_certificate_valid",
    "load_certificate",
    "load_pkcs12",
    "load_private_key",
    "save_certificate",
    "save_private_key",
]
